[package]
name = "pallet-example-mock-builder"
version = "4.0.0-dev"
authors.workspace = true
edition.workspace = true
license = "MIT-0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME pallet tested with mock-builder"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
frame-benchmarking = { path = "../../benchmarking", default-features = false, optional = true}
frame-support = { path = "../../support", default-features = false}
frame-system = { path = "../../system", default-features = false}
sp-io = { path = "../../../primitives/io", default-features = false}
sp-runtime = { path = "../../../primitives/runtime", default-features = false}
sp-std = { path = "../../../primitives/std", default-features = false}
polkadot-runtime-common = { path = "../../../../polkadot/runtime/common", default-features = false}

[dev-dependencies]
sp-core = { path = "../../../primitives/core", default-features = false}
mock-builder = { git = "https://github.com/foss3/runtime-pallet-library", branch = "polkadot-v1.2.0" }
polkadot-primitives = { path = "../../../../polkadot/primitives", default-features = false}

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
    "polkadot-runtime-common/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
    "polkadot-runtime-common/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
    "polkadot-runtime-common/try-runtime",
]
